[workspace]
exclude = [
  "prover"
]
members = [
  "crates/common",
  "crates/cli",
  "crates/node",
  "crates/shim",
  "crates/shim-ffi",
  "crates/tests/test-programs",
  "crates/tests/e2e-tests", "crates/common",
]
resolver = "2"
